"""change to to date and time

Revision ID: 0c85d27da92e
Revises: 84f53900d351
Create Date: 2018-08-11 07:01:59.814027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c85d27da92e'
down_revision = '84f53900d351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'data pesanan', ['kode_pemesanan'])
    op.add_column('rute', sa.Column('jam', sa.Time(), nullable=True))
    op.create_foreign_key(None, 'user', 'PO', ['po_id'], ['id_po'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('rute', 'jam')
    op.drop_constraint(None, 'data pesanan', type_='unique')
    # ### end Alembic commands ###
