"""menukar tipe data jadwal_berangkat menjadi date dari datetime pada table data_pesanan

Revision ID: 641e8a5cfbd1
Revises: 8d1d40cb19f2
Create Date: 2018-08-12 15:33:03.151456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641e8a5cfbd1'
down_revision = '8d1d40cb19f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
