"""menambahkan kolom is_public pada table rute2

Revision ID: 6f22b11a0d1e
Revises: 722821b41758
Create Date: 2018-08-12 08:11:52.867690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f22b11a0d1e'
down_revision = '722821b41758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rute', sa.Column('is_public', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rute', 'is_public')
    # ### end Alembic commands ###
