"""menambahkan kolom is_public pada table rute

Revision ID: 722821b41758
Revises: 5d138f07c36b
Create Date: 2018-08-12 08:08:17.910890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722821b41758'
down_revision = '5d138f07c36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rute', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rute', 'is_public')
    # ### end Alembic commands ###
