"""1

Revision ID: 769fae7cfee4
Revises: 
Create Date: 2018-07-16 03:56:23.804573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '769fae7cfee4'
down_revision = None
branch_labels = None
depends_on = None

status_pembayaran = ENUM('pending', 'confirmed', 'rejected', name='status_pembayaran', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jadwal',
    sa.Column('id_jadwal', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(), nullable=True),
    sa.Column('jam', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_jadwal')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rute',
    sa.Column('id_rute', sa.Integer(), nullable=False),
    sa.Column('kode_rute', sa.String(), nullable=True),
    sa.Column('tujuan', sa.String(), nullable=True),
    sa.Column('ongkos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_rute')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('data pesanan',
    sa.Column('id_pemesan', sa.Integer(), nullable=False),
    sa.Column('kode_pemesan', sa.String(), nullable=True),
    sa.Column('nama_pemesan', sa.String(), nullable=True),
    sa.Column('nomor_telepon', sa.Numeric(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('rute_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_pemesanan', sa.DateTime(), nullable=True),
    sa.Column('tanggal_ingin_berangkat', sa.DateTime(), nullable=True),
    sa.Column('jam_ingin_berangkat', sa.String(), nullable=True),
    sa.Column('harga_tiket', sa.Integer(), nullable=True),
                    sa.Column('status_pembayaran', status_pembayaran, nullable=True),
    sa.ForeignKeyConstraint(['rute_id'], ['rute.id_rute'], ),
    sa.PrimaryKeyConstraint('id_pemesan'),
    sa.UniqueConstraint('kode_pemesan')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('data pesanan')
    op.drop_table('user')
    op.drop_table('rute')
    op.drop_table('role')
    op.drop_table('jadwal')
    # ### end Alembic commands ###
