"""menukar tipe data jadwal_berangkat menjadi date dari datetime pada table data_pesanan dan juga tanggal_lahir penumpang

Revision ID: 7b4479f2f973
Revises: 641e8a5cfbd1
Create Date: 2018-08-12 15:33:36.150823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4479f2f973'
down_revision = '641e8a5cfbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
