"""2

Revision ID: 81fb1052ae96
Revises: 769fae7cfee4
Create Date: 2018-07-16 04:10:14.794766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fb1052ae96'
down_revision = '769fae7cfee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
