"""menghapus kolom alamat pada table data_pesanan

Revision ID: 8d1d40cb19f2
Revises: fc333dc56677
Create Date: 2018-08-12 14:30:43.434869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1d40cb19f2'
down_revision = 'fc333dc56677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data pesanan', 'alamat_pemesan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data pesanan', sa.Column('alamat_pemesan', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
