"""menambahkan kolom nomor_telelpon pada table user

Revision ID: 957162e9d178
Revises: dd6b4e32d55a
Create Date: 2018-08-14 09:33:02.112299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957162e9d178'
down_revision = 'dd6b4e32d55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nomor_telepon', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nomor_telepon')
    # ### end Alembic commands ###
