"""menambahkan sifat nullable=True pada kolom jam

Revision ID: dd6b4e32d55a
Revises: f897eeacb797
Create Date: 2018-08-14 06:48:01.288840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6b4e32d55a'
down_revision = 'f897eeacb797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
