"""relasi table rute dengan table PO

Revision ID: e8b64062cf9a
Revises: 6f22b11a0d1e
Create Date: 2018-08-12 10:13:09.429174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b64062cf9a'
down_revision = '6f22b11a0d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rute', sa.Column('po_id', sa.Integer(), nullable=True))
    op.alter_column('rute', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'rute', 'PO', ['po_id'], ['id_po'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rute', type_='foreignkey')
    op.alter_column('rute', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('rute', 'po_id')
    # ### end Alembic commands ###
