"""relationship po_name pada table data_pesanan

Revision ID: ebe29ccfc151
Revises: 7b4479f2f973
Create Date: 2018-08-12 15:35:59.794543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe29ccfc151'
down_revision = '7b4479f2f973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
