"""testing tukar tipe data po_name menjadi string

Revision ID: ed5126f18f56
Revises: ebe29ccfc151
Create Date: 2018-08-12 16:25:04.163052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5126f18f56'
down_revision = 'ebe29ccfc151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data pesanan', sa.Column('po_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data pesanan', 'po_name')
    # ### end Alembic commands ###
