"""menambahkan kolom jumlah kursi pada table rute

Revision ID: f897eeacb797
Revises: ed5126f18f56
Create Date: 2018-08-14 03:57:06.106483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f897eeacb797'
down_revision = 'ed5126f18f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rute', sa.Column('jumlah_kursi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rute', 'jumlah_kursi')
    # ### end Alembic commands ###
