"""penambahan beberapa kolom pada table data_pesanan

Revision ID: fc333dc56677
Revises: e8b64062cf9a
Create Date: 2018-08-12 14:14:15.557761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc333dc56677'
down_revision = 'e8b64062cf9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data pesanan', sa.Column('alamat_pemesan', sa.String(), nullable=True))
    op.add_column('data pesanan', sa.Column('email_pemesan', sa.VARCHAR(), nullable=True))
    op.add_column('data pesanan', sa.Column('jumlah_kursi_yang_di_booking', sa.Integer(), nullable=True))
    op.add_column('data pesanan', sa.Column('nama_penumpang', sa.String(), nullable=True))
    op.add_column('data pesanan', sa.Column('nomor_telepon_pemesan', sa.VARCHAR(), nullable=True))
    op.add_column('data pesanan', sa.Column('tanggal_lahir_penumpang', sa.DateTime(), nullable=True))
    op.add_column('data pesanan', sa.Column('title_penumpang', sa.String(), nullable=True))
    op.drop_column('data pesanan', 'nomor_telepon')
    op.drop_column('data pesanan', 'jumlah_kursi')
    op.drop_column('data pesanan', 'tanggal_lahir')
    op.drop_column('data pesanan', 'alamat')
    op.alter_column('rute', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rute', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('data pesanan', sa.Column('alamat', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('data pesanan', sa.Column('tanggal_lahir', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('data pesanan', sa.Column('jumlah_kursi', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('data pesanan', sa.Column('nomor_telepon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('data pesanan', 'title_penumpang')
    op.drop_column('data pesanan', 'tanggal_lahir_penumpang')
    op.drop_column('data pesanan', 'nomor_telepon_pemesan')
    op.drop_column('data pesanan', 'nama_penumpang')
    op.drop_column('data pesanan', 'jumlah_kursi_yang_di_booking')
    op.drop_column('data pesanan', 'email_pemesan')
    op.drop_column('data pesanan', 'alamat_pemesan')
    # ### end Alembic commands ###
